sudo: false
language: node_js
node_js:
  - '0.12'

addons:
  postgresql: "9.4"
  
services:
  - rabbitmq

before_script:
  - psql -c 'create database livetable_test;' -U postgres

after_script:
  - npm run codeclimate && npm run coveralls
